resources:
- name: dev-postgres-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/dev-postgres

- name: dev-postgres-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-postgres

- name: dev-postgres-ifb-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/dev-postgres-ifb

- name: dev-postgres-ifb-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-postgres-ifb

- name: dev-mysql-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/dev-mysql

- name: dev-mysql-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-mysql

- name: dev-mysql-5.6-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/dev-mysql-5.6

- name: dev-mysql-5.6-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-mysql-5.6

- name: deploy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/deploy

- name: deploy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy

- name: small-git-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/small-git

- name: small-git-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/small-git

- name: deploy-light-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci/dockerfiles/deploy-light

- name: deploy-light-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy-light

- name: golang-1.x-tarball
  type: s3
  source:
    endpoint: storage.googleapis.com
    bucket: golang
    regexp: 'go(1\.\d+(\.\d+)?)\.linux-amd64\.tar.gz'

- name: cf-networking-release-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-networking-release
    branch: develop
    paths:
      - ci

- name: deploy-light-image-version
  type: semver
  source:
    driver: s3
    region_name: us-west-2
    bucket: docker-image-versions
    key: light-image/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    initial_version: 0.0.1

jobs:
- name: build-dev-postgres-image
  plan:
  - aggregate:
    - get: cf-networking-release-ci
    - get: dev-postgres-dockerfile
      trigger: true
    - get: golang-1.x-tarball
      trigger: true
  - task: add-golang
    file: cf-networking-release-ci/ci/tasks/add-golang-to-docker-context.yml
    input_mapping:
      dockerfile: dev-postgres-dockerfile
    params:
      INPUT_DOCKERIMAGE_PATH: dockerfile/ci/dockerfiles/dev-postgres
  - put: dev-postgres-image
    params:
      build: docker-build-context


- name: build-dev-postgres-ifb-image
  plan:
  - aggregate:
    - get: cf-networking-release-ci
    - get: dev-postgres-ifb-dockerfile
      trigger: true
    - get: golang-1.x-tarball
      trigger: true
  - task: set-docker-image-tag
    file: cf-networking-release-ci/ci/tasks/set-docker-image-tag.yml
    input_mapping:
      dockerfile: dev-postgres-ifb-dockerfile
    params:
      TAG: 4.9.49
  - task: add-golang
    file: cf-networking-release-ci/ci/tasks/add-golang-to-docker-context.yml
    input_mapping:
      dockerfile: dev-postgres-ifb-dockerfile
    params:
      INPUT_DOCKERIMAGE_PATH: dockerfile/ci/dockerfiles/dev-postgres-ifb
  - put: dev-postgres-ifb-image
    params:
      build: docker-build-context
      build_args:
        KERNELVER: 4.9.36
      tag: docker-image-tag-path/tag

- name: build-dev-mysql-image
  plan:
  - aggregate:
    - get: cf-networking-release-ci
    - get: dev-mysql-dockerfile
      trigger: true
    - get: golang-1.x-tarball
      trigger: true
  - task: add-golang
    file: cf-networking-release-ci/ci/tasks/add-golang-to-docker-context.yml
    input_mapping:
      dockerfile: dev-mysql-dockerfile
    params:
      INPUT_DOCKERIMAGE_PATH: dockerfile/ci/dockerfiles/dev-mysql
  - put: dev-mysql-image
    params:
      build: docker-build-context

- name: build-dev-mysql-5.6-image
  plan:
  - aggregate:
    - get: cf-networking-release-ci
    - get: dev-mysql-5.6-dockerfile
      trigger: true
    - get: golang-1.x-tarball
      trigger: true
  - task: add-golang
    file: cf-networking-release-ci/ci/tasks/add-golang-to-docker-context.yml
    input_mapping:
      dockerfile: dev-mysql-5.6-dockerfile
    params:
      INPUT_DOCKERIMAGE_PATH: dockerfile/ci/dockerfiles/dev-mysql-5.6
  - put: dev-mysql-5.6-image
    params:
      build: docker-build-context

- name: build-deploy-image
  plan:
  - get: deploy-dockerfile
    trigger: true
  - put: deploy-image
    params:
      build: deploy-dockerfile/ci/dockerfiles/deploy

- name: build-small-git-image
  plan:
  - get: small-git-dockerfile
    trigger: true
  - put: small-git-image
    params:
      build: small-git-dockerfile/ci/dockerfiles/small-git

- name: build-deploy-light-image
  plan:
  - get: deploy-light-image-version
    params: {bump: minor}
  - get: deploy-light-dockerfile
    trigger: true
  - task: set-docker-image-tag
    file: cf-networking-release-ci/ci/tasks/set-docker-image-tag.yml
    input_mapping:
      dockerfile: dev-postgres-ifb-dockerfile
    params:
      TAG: deploy-light-image-version
  - put: deploy-light-image-version
    params: {file: docker-version/version}
  # - put: deploy-light-image
  #   params:
  #     build: deploy-light-dockerfile/ci/dockerfiles/deploy-light
